---
# yamllint disable rule:line-length
name: Shell Check

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check scripts with shellcheck
        run: |
          shellcheck *.sh
